default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prediction_chicken_development
  host: localhost
  port: 5432
  username: postgres
  password: password # don't judge me

test:
  <<: *default
  database: prediction_chicken_test
  host: localhost
  port: 5432
  username: postgres
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>